name: Deploy to GitHub pages
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: npm i
      - run: npm run deploy

      - name: Init new repo in dist folder and commit generated files
        run: |
          cd dist
          git init
          git add -A
          git commit -m 'deploy'
      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./dist
