name: Deploy to GitHub pages
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
      - name: Generate static Gridsome files
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: npm i
      - run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          npm run deploy

      - name: Init new repo in dist folder and commit generated files
        run: |
          cd dist
          git init
          git add -A
          git commit -m 'deploy'
      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./dist
