name: Deploy to GitHub pages
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Install dependencies
        run: |
          npm install --global @gridsome/cli
          npm i

      - name: Build static files
        run: gridsome build

      - name: Init new repo in dist folder and commit generated files
        run: |
          cd dist
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'
          
      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./dist
